version: "3"
services:
  tests:
    image: integration-tests:${BUILD_COUNTER:-0}
    command: ["./wait-for-it.sh", "selenium-hub:4444", "--", "npm", "test", "--", "--hostname", "selenium-hub"]
    depends_on:
      - selenium-hub
    environment:
      - HOST=selenium-hub
      - E2E_TEST_URL=tests:3003
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    container_name: selenium-hub
    expose:
      - "4444"
  chrome:
    image: selenium/node-chrome:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    links:
      - tests
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - CHROME_VERSION=62.0.3202.94
    logging:
      driver: none

